import { ArrowLeft, ArrowUpRight, Check, X } from 'lucide-react';
import type { Product } from '@/types/catalogue';

interface ProductDetailProps { product: Product; onClose: () => void; onVisualize: (product: Product) => void; }

export function ProductDetail({ product, onClose, onVisualize }: ProductDetailProps) {
  const image = product.product_images?.[0]?.image_url;
  return <div className="detail-overlay" onClick={onClose}><aside className="detail-panel" onClick={(event) => event.stopPropagation()}><button className="detail-close" onClick={onClose}><X size={20} /></button><div className="detail-image">{image ? <img src={image} alt={product.image_alt ?? product.name ?? product.product_code} /> : <div className="image-placeholder">Product image coming soon</div>}</div><div className="detail-copy"><button className="back-link" onClick={onClose}><ArrowLeft size={15} /> Back to collection</button><p className="eyebrow">{product.categories?.name ?? 'Collection'} / {product.product_code}</p><h2>{product.name ?? 'Catalogue product'}</h2><p className="detail-description">{product.description ?? 'Product details are being carefully prepared. Ask our team for availability, sizes and recommendations.'}</p><div className="spec-grid"><div><span>Category</span><strong>{product.categories?.name ?? '—'}</strong></div><div><span>Size / type</span><strong>{product.sizes?.join(', ') || 'On request'}</strong></div><div><span>Finish</span><strong>{product.finish ?? 'On request'}</strong></div><div><span>Colour</span><strong>{product.colour ?? 'On request'}</strong></div></div><div className="detail-note"><Check size={16} /> Original catalogue product — visualizations preserve its reference image.</div><div className="detail-actions"><button className="button button-primary" onClick={() => onVisualize(product)}>Visualize in my room <ArrowUpRight size={16} /></button><a className="button button-outline" href="#contact" onClick={onClose}>Ask for availability</a></div></div></aside></div>;
}
