import { ArrowRight, ImagePlus, Sparkles, Upload } from 'lucide-react';
import { useState } from 'react';
import type { Product } from '@/types/catalogue';

export function Visualizer({ selectedProduct, onBack }: { selectedProduct: Product | null; onBack: () => void }) {
  const [room, setRoom] = useState('Bathroom');
  const [surface, setSurface] = useState('Wall');
  const [uploaded, setUploaded] = useState(false);
  const rooms = ['Bathroom', 'Kitchen', 'Living room', 'Bedroom', 'Outdoor'];
  return <main className="visualizer-page"><div className="page-intro"><span className="eyebrow">AI DESIGN STUDIO / 01</span><h1>See your space<br /><em>in a new light.</em></h1><p>Use your room as the starting point. When connected, the visualizer will preserve your layout and apply the selected real Mohammedi product to the chosen surface.</p></div><div className="visualizer-shell"><div className="visualizer-steps"><div className="step active"><b>01</b><span>Your room</span></div><div className="step"><b>02</b><span>Choose a product</span></div><div className="step"><b>03</b><span>Visualize</span></div></div><div className="visualizer-workspace"><div className="upload-zone" onClick={() => setUploaded(true)}>{uploaded ? <><ImagePlus size={30} /><strong>Room photo selected</strong><span>Ready for the visualizer</span></> : <><Upload size={30} /><strong>Upload a photo of your room</strong><span>JPG or PNG · We preserve your perspective</span><button className="text-button">Choose photo <ArrowRight size={15} /></button></>}</div><div className="visualizer-controls"><label>Room type</label><div className="pill-row">{rooms.map((item) => <button key={item} className={room === item ? 'selected' : ''} onClick={() => setRoom(item)}>{item}</button>)}</div><label>Apply the product to</label><div className="pill-row"><button className={surface === 'Floor' ? 'selected' : ''} onClick={() => setSurface('Floor')}>Floor</button><button className={surface === 'Wall' ? 'selected' : ''} onClick={() => setSurface('Wall')}>Wall</button><button className={surface === 'Both' ? 'selected' : ''} onClick={() => setSurface('Both')}>Both</button></div><div className="selected-product"><span className="eyebrow">SELECTED PRODUCT</span><strong>{selectedProduct?.name ?? 'Choose from the collection'}</strong><span>{selectedProduct?.product_code ?? 'No product selected'}</span></div><button className="button button-primary full-width" onClick={onBack}><Sparkles size={16} /> {selectedProduct ? 'Return to product' : 'Browse products first'}</button></div></div></div><div className="visualizer-disclaimer"><span>Accurate by design</span><p>AI-generated scenes are inspirational visualizations. The original product image remains the source of truth and is clearly distinguished from generated surroundings.</p></div></main>;
}
